### ISSUE TITLE
Proposal review 11/7/18

### ISSUE THREAD

**Issue by BCrawfordScott** [ssoonmi/MiTube#1]
### MVP List: 
 - [x] See Matthias email about the YouTube MVP list and make the necessary tweaks.

### Schema: 
- [x] Move Users, Videos, Comments, Likes to the top of the list.
- [x] List Channels and Subscriptions as bonus tables 

- Likes as a polymorphic association looks great, and the structure of your tables looks really good.
Let me know if you have any questions.

**Comment by ssoonmi** [comment]
I feel like channels are an integral part of viewing all the videos uploaded by a user. Do channels have to be a bonus feature? I connected a video to a channel, not to an owner. A video is connected to the owner by the owner of the channel it is connected to.

**Comment by BCrawfordScott** [comment]
Then let's keep it and use that structure.  I totally agree with you that it is logical (and it's exactly how youtube organizes it's data).  The reason I suggested not including it was because it wasn't part of the prescribed MVPs, but I'm totally on board with keeping channels in if it's what you want.

**Comment by ssoonmi** [comment]
Great! Thank you!
